### ISSUE TITLE
Doesn't work with rails 6.0

### ISSUE THREAD

**Issue by DCrow** [composite-primary-keys/composite_primary_keys#543] opened 2021-02-03 14:30 UTC
Having problems upgrading to 6.0 from 5.2.

In rails 5.2 this code was working correctly, but for 6.0 this always fails.
```ruby
OrderPosition.create(id: [1, 2], name: 'Burger')
```

The resulting SQL is different
```
# 5.2
OrderPosition Create (0.4ms)  INSERT INTO "order_positions" ("id", "subid", "name") VALUES ($1, $2, $3) RETURNING "id","subid"  [["id", 1], ["subid", 2], ["name", "Burger"]]
# 6.0
OrderPosition Create (0.9ms)  INSERT INTO "order_positions" ("name") VALUES ($1) RETURNING "id","subid"  [["name", "Burger"]]
```

Example table is defined as follows
```sql
create table order_positions (
  id int not null,
  subid int not null,
  name varchar(255) not null,
  primary key (id, subid)
);
```

An [example](https://github.com/DCrow/composite_primary_keys/commit/68b7d05229d7b2f927e2f5c1f6d59597c68ed88e) demonstrating this error.

**Comment by cfis** [comment] 2021-02-04 03:22
Thanks for the test case. Will take a look.

**Comment by DCrow** [comment] 2021-02-15 13:38
@cfis Any progress on this issue?

**Comment by cfis** [comment] 2021-02-15 21:03
Sorry not yet. Tried yesterday but ran into bundler issues that I needed to resolve. 
https://github.com/rubygems/rubygems/issues/4375

**Comment by cfis** [comment] 2021-02-16 01:42
Ok, at least on mysql this seems to be working fine for me. I added a test case that should be the same as the one you sent in - can you look?

What database are you using, perhaps its something database specific.

**Comment by DCrow** [comment] 2021-02-16 07:52
Yes, your test case works in my case too. 
It seems that the problem is with this
```
self.primary_keys = [:id, :subid]
```
In your case the primary keys are `[:tariff_id, :start_date]`. 
My guess is that `id` field in the table is the problem.

In master branch I still can reproduce this problem in my example using MySQL and Postgresql.

**Comment by DCrow** [comment] 2021-03-01 13:31
@cfis Any luck so far?

**Comment by cfis** [comment] 2021-03-01 18:30
Sorry didn't see your response. So I assume the :id field is the issue. There were some commits a while back to try and support having a field name using :id, previously that was a no go with CPK.

Anyway, will look again.

**Comment by DCrow** [comment] 2021-04-27 09:36
@cfis Sorry to bother you again. Has there been any progress?

**Comment by cfis** [comment] 2021-04-29 03:12
Ah sorry, not yet...thanks for the reminder.

**Comment by cfis** [comment] 2021-05-01 03:06
If you update the code like this:

```ruby
    OrderPosition.create!(:id => 1, :subid => 2, :name => 'Burger')
```

It works:

```
 OrderPosition Create (1.8ms)  INSERT INTO "order_positions" ("id", "subid", "name") VALUES ($1, $2, $3) RETURNING "id","subid"  [["id", 1], ["subid", 2], ["name", "Burger"]]
```

**Comment by cfis** [comment] 2021-05-01 07:07
See code here:

https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/active_model/attribute_assignment.rb

See this commit:

https://github.com/composite-primary-keys/composite_primary_keys/commit/b0413f5d6a85a341ad0ac7417430007bfcee63d0

Happy to review a pull request if you can come up with a better way of doing this.

**Comment by DCrow** [comment] 2021-05-04 07:28
> If you update the code like this:
> ```ruby 
> OrderPosition.create!(:id => 1, :subid => 2, :name => 'Burger')
> ```

This does work but I wanted to say that previously in 5.2
```ruby
OrderPosition.create!(id: [1, 2], name: 'Burger')
```
also worked. 
In my project there are a lot of places where `id` is sent from js app to rails backend as an array. And it's not possible to change this behavior client side...
Which is why I needed this functionality from 5.2 version.

Isn't it possible to port some of the code used for this functionality in 5.2 to 6.0?

Also as you pointed out after that commit `to_json` starts to returns a different result
Instead of `{\"id\":[1,2],\"subid\":2,\"name\":\"Burger\"}`
I get `{\"id\":1,\"subid\":2,\"name\":\"Burger\"}`

**Comment by cfis** [comment] 2021-05-04 23:16
The problem is that 5.2 was broken for people trying to use :id for a specific field in the key - which came up a few times. So going back to that doesn't really help.

Basically we want :id to mean 2 different things. To rails the :id method is the primary key (no matter the underlying column name) thus that's the same for cpk. Except when we want it to mean one specific column that is called :id. In my view having an :id column in a composite primary key is weird, but I get that it happens and db's schemas can't be changed. So the change in Rails 6 was to try and straddle that divide.

Perhaps there can be an added check to see if the passing value is an array or not, I haven't looked at that code in a while so not sure if that would work or not.

**Comment by DCrow** [comment] 2021-05-06 08:01
Isn't it still a problem in Rails? 

When you have a key called :id which is not a primary key, and another key which is a primary key in the same table. 
Then `id` method returns value from the primary key and not from underlying :id column.
I do understand that this is a rare case, but it does happen.

Which is why I'm not sure that this helped?

Maybe add some kind of config to alter between current behavior and previous?

**Comment by cfis** [comment] 2021-05-09 06:27
Ok, this should be fixed.

**Closed by cfis** 2021-05-09 06:27 UTC

**Comment by DCrow** [comment] 2021-05-11 08:14
Thanks!

And it seems after b0413f5 `to_json` also stopped returning an array for `id`. 
Is there any way to revert this to old behavior?

**Comment by cfis** [comment] 2021-05-12 01:54
In that case, I don't see a way we can distinguish the two cases (id method versus id attribute).

**Comment by DCrow** [comment] 2021-05-13 07:54
Yes, and as far as I understand this behavior(when id returns primary key values instead of attribute) should be correct. 
See https://github.com/rails/rails/issues/34402 for more details.

**Comment by cfis** [comment] 2021-05-31 04:17
Yeah, sorry, I know that's annoying....
