### ISSUE TITLE
Update model nested attributes with composite foreign key in rails fails

### ISSUE THREAD

**Issue by danicuki** [composite-primary-keys/composite_primary_keys#302] opened 2015-06-05 19:42 UTC
http://stackoverflow.com/questions/30674468/update-model-nested-attributes-with-composite-foreign-key-in-rails

**Comment by aruprakshit** [comment] 2015-06-05 21:38
+1

**Comment by cfis** [comment] 2015-06-05 23:30
Hmm, sounds like a bug.  There should be tests for this in CPK.  Could you take a look at see if one is applicable, and if not, write one that shows the problem?  That would be super helpful to getting it fixed.

**Comment by prgjazz** [comment] 2016-11-27 23:27
Hi all,
still issue there on Rails 5 and CBK 9.0.4.

Someone want to collaborate to solve it? Is a blocking issue for me.

Contact me, please.

**Comment by prgjazz** [comment] 2016-11-27 23:44
Confirmed the issue happens only when there are composite primary keys; moving to single primary key it does not happen.

The problem stands when rails searches for nested record: the first attribute of the composite primary key is populated with correct value, next are all NULL.

Here I have a master table ("clienti") and the nested table ("destinazione_clienti") with composite primary key composed by columns "cliente_codice" and "societa". During insert, everything good, during update, rails stop at this query:
SELECT `destinazioni_clienti`.* FROM `destinazioni_clienti` WHERE `destinazioni_clienti`.`cliente_codice` = 22630 AND (`destinazioni_clienti`.`cliente_codice` = 22630 AND `destinazioni_clienti`.`societa` IS NULL)

The problem is in the "IS NULL", since in this example "societa" was populated.

**Comment by cfis** [comment] 2017-05-22 06:42
Coming back to this.  Can you create a test case using the test data in CPK?  That would be quite helpful in tracking it down.

**Closed** 2017-10-09 01:22 UTC

**Comment by dvergeylen** [comment] 2018-02-05 12:02
I have exactly the same problem that @prgjazz describes. How can I help on this?

**Comment by dvergeylen** [comment] 2018-02-05 12:15
I think the problem lies in the ID_SEP, which is set to "," but in my case is " " (space):

Nested Composite key id is encoded like this (Rails 5.1):
```
"id"=>"35763 197 1"
```

I guess the first argument is populated via other parsing, the nested ones from a split somehow:
```ruby
a, b, c = "1 2 3".split(',') # b and c are nil
```

**Comment by dvergeylen** [comment] 2018-02-05 13:33
Found a workaround. In `fields_for`, add the `include_id: false` and set it manually:

```ruby
<%= f.fields_for :users, user, include_id: false do |user_form| %>
  [...]
 <%= user_form.hidden_field :id, value: user.id.to_s # gives "32842,18,1" %>
<% end %>
```
