### ISSUE TITLE
rails 3.2.21 'not a symbol'

### ISSUE THREAD

**Issue by ripple0328** [composite-primary-keys/composite_primary_keys#267] opened 2014-12-25 06:05 UTC
with composite_primary_keys (5.0.14)
TypeError: [:project_id, :property_number] is not a symbol

I saw this issue solved in 7.x.x patch, will this also apply to 5.0.x?

**Comment by cfis** [comment] 2015-01-10 08:22
Ok, going to close this as caused by 3rd party gem.  Thanks for reporting it though!

**Closed by cfis** 2015-01-10 08:22 UTC

**Comment by gonzoyumo** [comment] 2015-01-10 08:34
Just FYI, I'm not 100% sure it's really that Gem that is guilty. I mean, maybe that gems assumes a behavior that is broken when using composite_primary_keys. I didn't dig deeper enough though to verify it.

**Comment by cfis** [comment] 2015-01-10 08:40
Make sense, but I think I'll go ahead and leave this closed for now since it sounds like you came up with a solution for your problem.

**Comment by Vanuan** [comment] 2015-03-24 16:11
I have this error, even without bullet. I use 7.0.7
